info:
  version: 
  title: data_source_huaweicloud_as_configurations
  description: 
schemes:
  - https
host: huaweicloudstack.com
tags:
  - name: AS
paths:
  /autoscaling-api/v1/{project_id}/scaling_configuration:
    get:
      tag: AS
      operationId: List
