info:
  version: 
  title: data_source_huaweicloud_gaussdb_mysql_configuration
  description: 
schemes:
  - https
host: huaweicloudstack.com
tags:
  - name: GaussDBforMySQL
paths:
  /v3/{project_id}/configurations:
    get:
      tag: GaussDBforMySQL
      operationId: List
